name: Update News JSON
on:
  schedule:
    - cron: "10 4 * * *"  # 04:10 UTC ~ 06:10 Berlin
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build news.json
        run: |
          python3 scripts/build_news.py
      - name: Commit & push
        run: |
          git config user.name "news-bot"
          git config user.email "news-bot@users.noreply.github.com"
          git add data/news.json
          git commit -m "news: auto update" || echo "No changes"
          git push
